@startuml entity_linking

hide empty members
' skinparam linetype ortho

abstract CommonResourceVisitor {

}

interface ResourceVisitor {
    visit(e)
}

class LogicABResourceVisitor {
    +visit(e)
    // logic for AB resources
}

class LogicCDResourceVisitor {
    +visit(e)
    // logic for CD resouces
}

LogicABResourceVisitor ..> ResourceVisitor : implements
LogicCDResourceVisitor ..> ResourceVisitor : implements

LogicABResourceVisitor --> CommonResourceVisitor : extends
LogicCDResourceVisitor --> CommonResourceVisitor : extends

interface LinkedResource {
    accept(resourceVisitor)
}

class RelatedResource1 {
    + a
    + b
    + c
    + d
    + accept(resourceVisitor)
}

class RelatedResource2 {
    + a
    + b
    + c
    + d
    + accept(resourceVisitor)
}

RelatedResource1 ..> LinkedResource : implements
RelatedResource2 ..> LinkedResource : implements

note "Client use array of LinkedResource" as N1

circle Client

Client .. N1
N1 .. LinkedResource

LinkedResource <.. ResourceVisitor : visit

@enduml