@startuml EndpointRedirectionExtendClass

hide empty members

circle Client

package Api {

    package v1 {
        interface IV1Logic {
            actionA()
            actionB()
        }
        class V1Logic{
            +actionA()
            +actionB()
        }
    }

    package v2 {
        class V1Redirector {
            +actionA()
            +actionB()
        }
        class V2Logic {
            +actionC()
            +actionD()
        }
    }
}

V1Logic ..> IV1Logic : implement
V1Redirector ..> IV1Logic : implement
V2Logic --> V1Redirector : extends

note bottom of V1Redirector
    implement
    resource mapping
    mechanism
endnote

Client ..> V2Logic : call API

@enduml