@startuml ApiVersioning

' skinparam linetype ortho

hide empty members

circle Client

package Api {
    abstract class CommonLogic

    package v1 {
        interface IV1Logic {
            actionA()
            actionB()
        }
        class V1Logic{
            +actionA()
            +actionB()
        }
    }

    package v2 {
        interface IV2Logic {
            actionC()
            actionD()
        }
        class V2Logic {
            -oldV1Logic: V1Logic
            +actionC()
            +actionD()
        }
    }
}

V1Logic --> CommonLogic
V1Logic ..> IV1Logic : implement
V2Logic --> CommonLogic
V2Logic ..> IV2Logic : implement
V2Logic ..> IV1Logic : implement

Client -- V2Logic : call API
note left of V2Logic::oldV1Logic
    oldV1Logic.actionA()
    oldV1Logic.actionB()
endnote

note as N1
UML arrow specification
<img:legends.svg>
endnote

@enduml