@startuml layers

!define ICONURL https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v2.2.0

!includeurl ICONURL/common.puml
!includeurl ICONURL/material/laptop.puml
!includeurl ICONURL/material/dns.puml
!includeurl ICONURL/font-awesome/server.puml
!includeurl ICONURL/devicons/nginx.puml

hide empty members

' skinparam linetype ortho
' skinparam linetype polyline
skinparam defaultTextAlignment center

MATERIAL_LAPTOP(Client, Client)
rectangle Servers {
    FA_SERVER(Application,Application)
    DEV_NGINX(Proxy,Proxy)
}

database Database
MATERIAL_DNS(DNS,DNS)
MATERIAL_DNS(CDN,CDN)

Client <---> Application
Proxy <--> Client
Proxy <~~> Application
Application <--> Database
Client <~~> DNS
Client <~~> CDN

@enduml