@startuml content_negotiation

hide empty members

abstract BaseObject {
    {abstract} + String serialize()
}

class XmlObject {
    +serialize():String
}

class JsonObject {
    +serialize():String
}

class ObjectFactory {
    {static} + BaseObject getObject()
}

JsonObject --> BaseObject : extends
XmlObject --> BaseObject : extends

ObjectFactory -[hidden]- XmlObject
ObjectFactory -[hidden]- JsonObject

@enduml