@startmindmap api_evo_lit_review

*[#Orange]:API Evo
Liturature review;

**[#LightBlue]:RQ1: How has the field of
API evolution research evolved;

*** API evo research goal
**** New tools and Techniques
*****_ reduce complexity [155]
*****_ conserve familiarity [156]
*****_ organize changes [94, 165]

**** Empirical Studies
***** Data-mining Studies
******_ large sources of data

***** Case Studies
******_ specific system

***** User Studies
******_ learning barriers [79]
******_ API usage of an IDE [26]
******_ understand developers' deprecation neds [161]
******_ how api docs fails [179]
******_ usability of factory pattern in API [50]
******_ what make api hard to learn [151]
******_ pitfalls of unfamiliar APIs [47]
******_ API usability


**** Tools and techniques proposals
*****_ most API breaking changes are caused by refactoring
*****_:automatically detect API refactorings
(not complete and not evaluated);

**** Surveys
*****_:present an overview of a
subject using existing literature;

**** Datasets
*****_ conduct further studies [11]
*****_ advance the state-of-the-art [3]
*****_ improve reproducibility of research [162]

*** API evo research evaluation
**** Empirical evaluation
*****_:quantitative metrics
LOC, precision and recall, etc;

**** Case studies evaluation
*****_ examine single subject systems

**** User studies evaluation
*****_ Surveys
*****_ interviews

**** qualitative evaluation
*****_ subjective interpretations


*** API evo experimental subjects


@endmindmap