@startuml repository

' 777
' ff7b72
' FF4500
' background 0D1117

' skinparam backgroundColor transparent

' skinparam ArrowColor #777
' skinparam ArrowFontColor #777
' skinparam PackageBorderColor #777
' skinparam PackageFontColor #777

' ' skinparam ComponentBackgroundColor transparent
' ' skinparam ComponentFontColor #777
' skinparam ComponentBorderColor #777
' ' skinparam DatabaseBackgroundColor transparent
' ' skinparam DatabaseFontColor #777
' skinparam DatabaseBorderColor #777

hide empty members
' allow_mixing

component Controller

node uow1 as "Unit of Work" {
    component RepositoryA
}

node uow2 as "Unit of Work" {
    component RepositoryB
}

component DatabaseConnector


database SQL


Controller <.. RepositoryA : inject
Controller <.. RepositoryB : inject
RepositoryA .. DatabaseConnector
RepositoryB .. DatabaseConnector
DatabaseConnector .. SQL


@enduml